### PR TITLE
enhancement(slurmctld): Signal children processes

### LINKED ISSUE #37: Enable `SignalChildrenProcesses` by default
### Bug Description

Slurm process tracking is currently not configured to kill child processes of a job. Set `SignalChildrenProcesses=yes` in `cgroup.conf` to enable this functionality.

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jamesbeedy**
Slurm process tracking is currently not configured to kill child processes of a job. These changes set SignalChildrenProcesses=yes in cgroup.conf to enable this functionality.

Fixes #37

### CODE REVIEW

**Comment by jamesbeedy** [comment]
Closing this until slurm charms support the configuration.

**Comment by NucciTheBoss** [comment]
@jamesbeedy what specifically do you need for the charms to support this configuration in `cgroup.conf`. Do we need to modify which cgroup version is running on the machine?

**Comment by jamesbeedy** [comment]
> @jamesbeedy what specifically do you need for the charms to support this configuration in `cgroup.conf`? Do we need to modify which cgroup version is running on the machine?

Slurm > 23.02

**Comment by NucciTheBoss** [comment]
Ah, that'll do it. We'll have at least Slurm 23.11 once the fixes for the apt charm library are landed for Noble. Should be some time this week.

**Pull request closed without merging**
